# Generated by Django 2.2.6 on 2019-10-05 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('cleaning_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cleaning', serialize=False, to='hospital.Staff')),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
            ],
            options={
                'default_related_name': 'cleaning',
            },
            bases=('hospital.staff',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='doctor', serialize=False, to='hospital.Staff')),
                ('speciality', models.CharField(max_length=20)),
            ],
            options={
                'default_related_name': 'doctor',
            },
            bases=('hospital.staff',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nurse', serialize=False, to='hospital.Staff')),
            ],
            options={
                'default_related_name': 'nurse',
            },
            bases=('hospital.staff',),
        ),
    ]
