# Generated by Django 2.2.6 on 2019-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medicine_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
