# Generated by Django 2.2.6 on 2019-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20191005_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='cash_collection',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
