# Generated by Django 2.2.6 on 2019-10-05 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_pharmacy_cash_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tests', models.TextField()),
                ('fees', models.DecimalField(decimal_places=3, max_digits=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.Doctor')),
                ('medicines', models.ManyToManyField(related_name='medicines_prescribed', to='hospital.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_assistant_name', models.CharField(max_length=30)),
                ('lab_assistant_salary', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('diagnosis', models.ManyToManyField(related_name='diagnosis', to='hospital.Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('total_cash', models.DecimalField(decimal_places=3, max_digits=15)),
                ('role', models.IntegerField(choices=[(1, 'Director'), (2, 'Receptionist')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
